default: &default
  adapter: trilogy
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: streamer_watcher_development

test:
  <<: *default
  database: streamer_watcher_test
#
production:
  <<: *default
  database: streamer_watcher_production
  username: streamer_watcher
  password: <%= ENV["STREAMER_WATCHER_DATABASE_PASSWORD"] %>
